apiVersion: apps/v1
kind: Deployment
metadata:
  name: tv22
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tv22
  template:
    metadata:
      labels:
        app: tv22
    spec:
      containers:
      - name: tv22
        image: web/tv23
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: tv22
spec:
  selector:
    app: tv22
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
