apiVersion: apps/v1
kind: Deployment
metadata:
  name: bien-plus
  namespace: challenge

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bien-plus
  template:
    metadata:
      labels:
        app: bien-plus
    spec:
      containers:
      - name: bien-plus
        image: web/bien-plus
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: bien-plus
  namespace: challenge
spec:
  selector:
    app: bien-plus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
