apiVersion: apps/v1
kind: Deployment
metadata:
  name: intranet
  namespace: challenge

spec:
  replicas: 1
  selector:
    matchLabels:
      app: intranet
  template:
    metadata:
      labels:
        app: intranet
    spec:
      containers:
      - name: intranet
        image: web/intranet
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: intranet
  namespace: challenge
spec:
  selector:
    app: intranet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
